### PR TITLE
net module

### PR DESCRIPTION
**Pull request by aep**

### CODE REVIEW

**Comment by jwerle** [comment]
:rocket:

**Comment by jwerle** [comment]
Let me know when I should try this out

**Comment by aep** [comment]
This needs another complete redesign. 

The API doesn't work with the way winapi thinks about IO (you hand a buffer to the OS rather than getting a ready signal).

**Comment by aep** [comment]
reducing the scope of the PR to get this in. this is just the address parser and a bunch of compiler fixes for windows

**Pull request merged**
