### PR TITLE
feat: introduce 'weakmap' module in std

### PR DESCRIPTION
**Pull request by jwerle**
`weakmap::WeakMap` is a higher level `Map` abstraction for borrowed references.

### CODE REVIEW

**Comment by aep** [comment]
Having two modules that do the exact same thing in upstream sounds confusing.
I was assuming you just didnt like the map api and would like to change it, which is great.

**Comment by jwerle** [comment]
ah no this is just a small wrapper around `map` which is why I kept in userspace

**Comment by jwerle** [comment]
happy to close and keep there!

**Comment by aep** [comment]
allright. happy to accept api changes tho

**Comment by jwerle** [comment]
@aep cool `set()`, `has()`, and `clear()` are the only additions here, which just wrap `map::{insert_bb,get,remove}` methods

**Comment by aep** [comment]
yup, those are useful

**Pull request closed without merging**
