### PR TITLE
add repo support for 3rdparty modules

### PR DESCRIPTION
**Pull request by aep**
also move unfinished modules to nursery

### CODE REVIEW

**Comment by jwerle** [comment]
This is a great start! Thank you!

**Comment by jwerle** [comment]
I've been still working towards a HTTP(S) solution based on libcurl (for now) over here: https://github.com/zx-project/zx

**Comment by aep** [comment]
oh nice, those curl modules will come in handy. 

since your repo also has a modules/ structure, you should be able to use this repo in other projects now

**Comment by jwerle** [comment]
awesome

**Pull request merged**
